### PR TITLE
Sander

### PR DESCRIPTION
**Pull request by SaFrMo**
Added a function to allow user-uploaded SVGs - we've used this a couple times already, could be useful for the template

### CODE REVIEW

**Comment by drewbaker** [comment]
Why do we need get tags as string in the default template?

**Comment by SaFrMo** [comment]
If you're referring to my branch, get_tags_as_string actually isn't there any more - I reverted the commits that added it in. If there's a way to submit a pull request for a single commit, that's what I should've done instead - cherry-picking commit 6139695 on my branch would be the best thing to do.

**Comment by SaFrMo** [comment]
Added that check into the latest commit

**Comment by drewbaker** [comment]
May as well make it a function then, to address: https://github.com/funkhaus/style-guide/issues/9

**Comment by SaFrMo** [comment]
It actually already is a function, starting on line 495

**Comment by johndigital** [comment]
This looks good to me! Clear to merge if you are @drewbaker

**Comment by SaFrMo** [comment]
@drewbaker Or do you mean a function in page.php? Adding that in now!

**Comment by drewbaker** [comment]
Also, this would cause an error:

```
/*
 * Redirect to first child
 */
    function redirect_to_first_child ( $target_post = null ) {
        $target_post = get_post($target_post);
        $args = array(
            'child_of'      => $post->ID,
            'sort_column'   => 'menu_order'
        );
        $children = get_pages($args);
        if( isset($children[0]) and $first_child = $children[0] ) {
            wp_redirect( get_permalink($first_child->ID), 301 );
            exit;
        }
        return false;
    }
```

On the line `'child_of'      => $post->ID,` $post doesn't exist.

**Comment by drewbaker** [comment]
I'll rewrite this function now BTW, it can be done better.

**Comment by SaFrMo** [comment]
@drewbaker Sounds good!

**Comment by drewbaker** [comment]
This is the function you should use I think:

```
/*
 * Redirect to first child
 */
    function redirect_to_first_child ( $target_post = null ) {

        $target_post = get_post($target_post);

        $args = array(
            'post_type'         => get_post_type($target_post),
            'post_parent'       => $target_post->ID,
            'order'             => 'ASC',
            'orderby'           => 'menu_order',
            'fields'            => 'ids',
            'posts_per_page'    => 1
        );
        $children = get_posts($args);

        if( isset($children[0]) ) {
            wp_redirect( get_permalink($children[0]), 301 );
            exit;
        }

        return false;
    }
```

**Comment by SaFrMo** [comment]
Added and pushed that fix, @drewbaker and @jrobson153 - ready for review whenever!

**Pull request merged**
